<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.
Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does! 
You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

In [1]:
# setup all needed modules and configurations
import numpy as np
import numpy.ma as ma

# re-style the NumPy arrays
# remember to install needed module first:
# pip3 install numpy-html
%load_ext numpy_html

ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

Run the cell below to enable custom style for NumPy arrays:

In [2]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #dbc9e2 !important; color: black}
tr:nth-child(odd) {background: #e6afd3 !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [3]:
# exercise 1.1, create lists without NumPy
# use additional code cells or different variable names for each subtask

# list of 15 ones
list_of_ones = [1] * 15
list_of_ones


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [4]:
# list of 15 number 7's
list_of_sevens = [7] * 15
list_of_sevens

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [5]:
# list of numbers from 100 to 150
list_from_100_to_150 = list(range(100, 151))
list_from_100_to_150

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

In [6]:
# list of even numbers between 0 and 100
list_of_even_numbers = list(range(0, 101, 2))
list_of_even_numbers

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [7]:
# list of years that are divisible by 4 between 1950 and 2020
list_of_divisible_by_4 = [year for year in range(1950, 2021) if year % 4 == 0]
list_of_divisible_by_4

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [8]:
# exercise 1.2, create lists WITH NumPy
# use additional code cells or different variable names for each subtask

# array of 15 zeroes
array_of_zeroes = np.zeros(15)
array_of_zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# array of 15 ones
array_of_ones = np.ones(15)
array_of_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# array of 15 number 7's
array_of_sevens = np.full(15, 7)
array_of_sevens

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [11]:
# array of numbers from 100 to 150
array_from_100_to_150 = np.arange(100, 151)
array_from_100_to_150

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [12]:
# array of numbers from 1900 to 2021
array_from_1900_to_2021 = np.arange(1900, 2022)
array_from_1900_to_2021

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [13]:
# array of even numbers between 0 and 100
array_of_even_numbers = np.arange(0, 101, 2)
array_of_even_numbers

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
# array of years that are divisble by 4 between 1950 and 2020
array_of_divisible_by_4 = np.arange(1950, 2021, 4)
array_of_divisible_by_4

array([1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986, 1990,
       1994, 1998, 2002, 2006, 2010, 2014, 2018])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

I think it's propably easier and more simple with these kind of tasks than the plain Python code when you know how to use it. Or it seems like it.

<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [15]:
# exercise 1.3, NumPy vectors and matrices
# use different variable names for each subtask
# you can also make new code cells if you need

# a NumPy vector
vector = np.array([5, 16, 9, 2, 19, 18, 11, 7])

# find the position index of the largest value in the vector
index_of_max_value = np.argmax(vector)

# a 7x7 matric with values from 1 to 49
matrix = np.arange(1, 50).reshape(7, 7)

# a 8x8 random number matrix, values between 0 and 5
random_matrix = np.random.rand(8, 8) * 5

print("\nVector:\n\n", vector)

print("\nIndex of the largest value in the vector:\n\n", index_of_max_value)

print("\n7x7 Matrix:\n\n", matrix)

print("\n8x8 Random Number Matrix (values between 0 and 5):\n\n", random_matrix)


Vector:

 [ 5 16  9  2 19 18 11  7]

Index of the largest value in the vector:

 4

7x7 Matrix:

 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]

8x8 Random Number Matrix (values between 0 and 5):

 [[4.80222122e+00 1.51915059e+00 1.90131368e+00 3.55696483e+00
  4.09319312e+00 1.90395330e+00 4.00174944e+00 2.68759915e-05]
 [1.80109156e+00 1.01405759e+00 3.88248131e+00 4.30414488e+00
  2.52113968e+00 2.72989547e+00 3.50389059e-01 3.69218441e+00]
 [3.82986209e+00 2.42852160e+00 1.96642069e+00 2.75444569e+00
  2.90379420e+00 3.97118633e-01 4.04181661e+00 2.17429705e+00]
 [5.60232540e-01 1.74262955e+00 1.71105116e+00 3.99395439e+00
  4.55352193e-01 2.40571525e+00 4.68082770e-01 2.33686698e+00]
 [8.79199716e-01 3.89664247e-01 4.28373045e+00 4.56164711e+00
  4.49354848e+00 3.73763920e-01 3.95636867e+00 4.27434215e+00]
 [3.66815742e+00 6.00675096e-01 2.86183756e+00 3.2133

In [16]:
# extra task: a 7x7 matrix witout NumPy
matrix_without_numpy = [[i + 7 * j for i in range(1,8)] for j in range(7)]

print("\n7x7 Matrix Without NumPy:")
for row in matrix_without_numpy:
    print(row)


7x7 Matrix Without NumPy:
[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [17]:
# exercise 1.4, linspace
# use different variable names for each subtask
# you can also make new code cells if you need

# a linearly spaced array of 10 values between 0 and 1
linear_array = np.linspace(0, 1, 10)

# a 10x10 matrix between values 0 and 5
matrix_10x10 = np.linspace(0, 5, 100).reshape(10, 10)

print("Linearly spaced array between 0 and 1:\n\n", linear_array)

print("\n10x10 Matrix between 0 and 5:\n\n", matrix_10x10)

Linearly spaced array between 0 and 1:

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

10x10 Matrix between 0 and 5:

 [[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
  0.3030303  0.35353535 0.4040404  0.45454545]
 [0.50505051 0.55555556 0.60606061 0.65656566 0.70707071 0.75757576
  0.80808081 0.85858586 0.90909091 0.95959596]
 [1.01010101 1.06060606 1.11111111 1.16161616 1.21212121 1.26262626
  1.31313131 1.36363636 1.41414141 1.46464646]
 [1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
  1.81818182 1.86868687 1.91919192 1.96969697]
 [2.02020202 2.07070707 2.12121212 2.17171717 2.22222222 2.27272727
  2.32323232 2.37373737 2.42424242 2.47474747]
 [2.52525253 2.57575758 2.62626263 2.67676768 2.72727273 2.77777778
  2.82828283 2.87878788 2.92929293 2.97979798]
 [3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
  3.33333333 3.38383838 3.43434343 3.48484848]
 [3.5353

In [18]:
# extra task: a 10x10 matrix without Numpy
matrix_10x10_without_numpy = [[5 * (i + 10 * j) / 99 for i in range(10)] for j in range(10)]

print("\n10x10 Matrix Without NumPy:")
for row in matrix_10x10_without_numpy:
    print(row)


10x10 Matrix Without NumPy:
[0.0, 0.050505050505050504, 0.10101010101010101, 0.15151515151515152, 0.20202020202020202, 0.25252525252525254, 0.30303030303030304, 0.35353535353535354, 0.40404040404040403, 0.45454545454545453]
[0.5050505050505051, 0.5555555555555556, 0.6060606060606061, 0.6565656565656566, 0.7070707070707071, 0.7575757575757576, 0.8080808080808081, 0.8585858585858586, 0.9090909090909091, 0.9595959595959596]
[1.0101010101010102, 1.0606060606060606, 1.1111111111111112, 1.1616161616161615, 1.2121212121212122, 1.2626262626262625, 1.3131313131313131, 1.3636363636363635, 1.4141414141414141, 1.4646464646464648]
[1.5151515151515151, 1.5656565656565657, 1.6161616161616161, 1.6666666666666667, 1.7171717171717171, 1.7676767676767677, 1.8181818181818181, 1.8686868686868687, 1.9191919191919191, 1.9696969696969697]
[2.0202020202020203, 2.0707070707070705, 2.121212121212121, 2.1717171717171717, 2.2222222222222223, 2.272727272727273, 2.323232323232323, 2.3737373737373737, 2.424242424242

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [19]:
# exercise 1.5a, create matrix

# 3x5 matrix with NumPy
matrix_3x5 = np.arange(1, 16).reshape(3, 5)
matrix_3x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [20]:
# exercise 1.5b, generate NumPy array / matrix

# a NumPy array
numpy_array = np.random.rand(8, 16)
numpy_array

array([[0.36574823, 0.78588509, 0.6254027 , 0.41389621, 0.186184  ,
        0.74499989, 0.22238307, 0.22973397, 0.35276541, 0.23277585,
        0.98294856, 0.57016142, 0.32023998, 0.06811488, 0.00928329,
        0.83948751],
       [0.24894241, 0.66121829, 0.78867217, 0.76087727, 0.84983743,
        0.34224869, 0.99506071, 0.26557581, 0.53603452, 0.71231784,
        0.68771009, 0.74362934, 0.90270859, 0.78850462, 0.45634631,
        0.72538853],
       [0.27624135, 0.53846838, 0.12631979, 0.80379201, 0.21831741,
        0.58621651, 0.04043911, 0.82309293, 0.52948881, 0.66051065,
        0.19396655, 0.1240097 , 0.175808  , 0.84149802, 0.04912891,
        0.40038462],
       [0.60891948, 0.59497998, 0.2343487 , 0.32650734, 0.43861644,
        0.12283992, 0.14104193, 0.69802601, 0.06483105, 0.57934864,
        0.31059781, 0.31645322, 0.63425738, 0.29791686, 0.7331485 ,
        0.56924176],
       [0.28941725, 0.2845363 , 0.60456515, 0.72417963, 0.22225043,
        0.98036074, 0.04995053, 0.24291573, 0.07624851, 0.43445545,
        0.46300878, 0.78623277, 0.0895754 , 0.09726336, 0.03187   ,
        0.63270329],
       [0.57412021, 0.64928003, 0.5664275 , 0.36041338, 0.59260893,
        0.07223691, 0.93446744, 0.63880525, 0.72038376, 0.55723756,
        0.1145788 , 0.40867829, 0.60691676, 0.83448331, 0.48859117,
        0.9359701 ],
       [0.58159792, 0.86365125, 0.84651046, 0.93594982, 0.1641592 ,
        0.60271956, 0.1198932 , 0.34471712, 0.17255121, 0.5036847 ,
        0.49736638, 0.55387724, 0.09577901, 0.60332933, 0.44295337,
        0.53937041],
       [0.25225362, 0.20873584, 0.69087979, 0.49399353, 0.12321072,
        0.4065932 , 0.86054507, 0.85490844, 0.63619361, 0.95212475,
        0.78678109, 0.83654527, 0.41988755, 0.3653428 , 0.25816753,
        0.26701772]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [21]:
# exercise 1.5c, generate NumPy array / matrix

# a 10x10 NumPy array
array_10x10 = np.arange(1, 101).reshape(10, 10)
array_10x10

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [22]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)

# matrix slicing
sliced_submatrix = dataset[1:4, 2:5]
first_two_rows = dataset[:2, :]
last_three_columns = dataset[:, -3:]

print("Original Dataset Matrix:\n\n", dataset)

print("\nSliced Submatrix:\n\n", sliced_submatrix)

print("\nFirst Two Rows:\n\n", first_two_rows)

print("\nLast Three Columns:\n\n", last_three_columns)

Original Dataset Matrix:

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sliced Submatrix:

 [[ 9 10 11]
 [15 16 17]
 [21 22 23]]

First Two Rows:

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Last Three Columns:

 [[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]
 [28 29 30]
 [34 35 36]]


- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [23]:
# exercise 1.6b, matrix slicing

dataset = np.arange(1, 37).reshape(6, 6)

# a slice for the right bottom corner (3x4)
right_bottom_slice = dataset[-3:, 2:]

print("\nSlice of the right bottom corner (3x4):")
right_bottom_slice


Slice of the right bottom corner (3x4):


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [24]:
# exercise 1.6c, matrix slicing

dataset = np.arange(1, 37).reshape(6, 6)

column_slice = dataset[0:4:, 3:4]

print("\nPicked Column Slice (4x1):")
column_slice


Picked Column Slice (4x1):


array([[ 4],
       [10],
       [16],
       [22]])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [25]:
# exercise 1.6d, matrix slicing

dataset = np.arange(1, 37).reshape(6, 6)

row_slice = dataset[2, :]

print("\nPicked Row Slice (1x6):")
row_slice


Picked Row Slice (1x6):


array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [26]:
# exercise 1.6e, matrix slicing

dataset = np.arange(1, 37).reshape(6, 6)

three_rows_slice = dataset[3:, :]

print("\nPicked Three Rows Slice (3x6):")
three_rows_slice


Picked Three Rows Slice (3x6):


array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python!

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [27]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)

# use different variable names for each subtask
# you can also make new code cells if you need

# add 50 to all values in array (broadcasting)
dataset_2 += 50

# the sum of all values in the dataset
total_sum = np.sum(dataset_2)

# the sum of only odd numbers in the dataset
odd_sum = np.sum(dataset_2[dataset_2 % 2 != 0])

# the standard deviation of the values in the dataset
standard_deviation = np.std(dataset_2)

# the sum of all values by row in the dataset
row_sums = np.sum(dataset_2, axis=1)

# the sum of all values by column in the dataset
column_sums = np.sum(dataset_2, axis=0)

print("Modified Dataset (added 50):\n\n", dataset_2)

print("\nTotal Sum of All Values in the Dataset:\n\n", total_sum)

print("\nTotal Sum of Only Odd Numbers in the Dataset:\n\n", odd_sum)

print("\nStandard Deviation of the Values in the Dataset:\n\n", standard_deviation)

print("\nSum of All Values by Row in the Dataset:\n\n", row_sums)

print("\nTotal Sum of All Values by Column in the Dataset:\n\n", column_sums)


Modified Dataset (added 50):

 [[51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78]
 [79 80 81 82 83 84 85]
 [86 87 88 89 90 91 92]
 [93 94 95 96 97 98 99]]

Total Sum of All Values in the Dataset:

 3675

Total Sum of Only Odd Numbers in the Dataset:

 1875

Standard Deviation of the Values in the Dataset:

 14.142135623730951

Sum of All Values by Row in the Dataset:

 [378 427 476 525 574 623 672]

Total Sum of All Values by Column in the Dataset:

 [504 511 518 525 532 539 546]


In [28]:
# extra task: without NumPy

dataset_2 = np.arange(1, 50).reshape(7, 7)

# add 50 to all values
for i in range(len(dataset_2)):
    for j in range(len(dataset_2[i])):
        dataset_2[i][j] += 50

# total sum of all values
total_sum_without_numpy = sum(sum(row) for row in dataset_2)

# sum of only odd numbers
odd_sum_without_numpy = sum(num for row in dataset_2 for num in row if num % 2 != 0)

# sum of all values by row
row_sums_without_numpy = [sum(row) for row in dataset_2]

# sum of all values by column
columns_sums_without_numpy = [sum(row[i] for row in dataset_2) for i in range(len(dataset_2[0]))]

print("\nModified Dataset (added 50) without NumPy:\n\n", dataset_2)

print("\nTotal Sum of All Values in the Dataset without NumPy:\n\n", total_sum_without_numpy)

print("\nSum of Only Odd Numbers in the Dataset without NumPy:\n\n", odd_sum_without_numpy)

print("\nSum of All Values by Row in the Dataset without NumPy:\n\n", row_sums_without_numpy)

print("\nSum of All Values by Column in the Dataset without NumPy:\n\n", columns_sums_without_numpy)


Modified Dataset (added 50) without NumPy:

 [[51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78]
 [79 80 81 82 83 84 85]
 [86 87 88 89 90 91 92]
 [93 94 95 96 97 98 99]]

Total Sum of All Values in the Dataset without NumPy:

 3675

Sum of Only Odd Numbers in the Dataset without NumPy:

 1875

Sum of All Values by Row in the Dataset without NumPy:

 [378, 427, 476, 525, 574, 623, 672]

Sum of All Values by Column in the Dataset without NumPy:

 [504, 511, 518, 525, 532, 539, 546]


<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [29]:
# advanced extra exercise 1


<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [30]:
# advanced extra exercise 2
import numpy.ma as ma

# a NumPy matrix with numbers between 0 to 50
matrix = np.random.randint(0, 51, size=(5, 10))

# faulty numbers represented by -100 in 10 different spots
faulty_spots = np.random.choice(np.arange(5*10), size=10,replace=False)
matrix.ravel()[faulty_spots] = -100

# a masked array to handle the -100 values
masked_matrix = ma.masked_equal(matrix, -100)

# replace every -100 with 0
masked_matrix = ma.filled(masked_matrix, 0)

print("Original Matrix:\n\n", matrix)

print("\nMasked Array with -100 replaced by 0:\n\n", masked_matrix)

Original Matrix:

 [[  21    9   34   16 -100   15   42 -100   48   36]
 [  19    0   22   36   13    8   21   46 -100   18]
 [-100   43   22    8 -100 -100   25   47   17   31]
 [  25   38    8   45   37   21   47    6    2 -100]
 [  39   23   44   47    1   11 -100 -100 -100   25]]

Masked Array with -100 replaced by 0:

 [[21  9 34 16  0 15 42  0 48 36]
 [19  0 22 36 13  8 21 46  0 18]
 [ 0 43 22  8  0  0 25 47 17 31]
 [25 38  8 45 37 21 47  6  2  0]
 [39 23 44 47  1 11  0  0  0 25]]


<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [31]:
# advanced extra exercise 3

np.random.seed(42)

# random manufacturing years of 10 cars (values between 2010 and 2020)
manufacturing_years = np.random.randint(2010, 2021, 10)

# random selling prices of 10 cars (prices between 2000€ and 60000€)
selling_prices = np.random.randint(2000, 60001, 10)

# sort both datasets according to manufacturing years (argsort)
sorted_indices = np.argsort(manufacturing_years)

sorted_manufacturing_years = manufacturing_years[sorted_indices]
sorted_selling_prices = selling_prices[sorted_indices]

print("Original Manufacturing Years:\n\n", manufacturing_years)

print("\nOriginal Selling Prices:\n\n", selling_prices)

print("\nSorted Manufacturing Years:\n\n", sorted_manufacturing_years)

print("\nSorted Selling Prices:\n\n", sorted_selling_prices)

Original Manufacturing Years:

 [2016 2013 2020 2017 2014 2016 2019 2012 2016 2020]

Original Selling Prices:

 [23962 49191 46131 18023 43090  3685  2769 58101  4433  7311]

Sorted Manufacturing Years:

 [2012 2013 2014 2016 2016 2016 2017 2019 2020 2020]

Sorted Selling Prices:

 [58101 49191 43090 23962  3685  4433 18023  2769 46131  7311]


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




In [32]:
# advanced extra exercise 4

# np.repeat() is useful for replicating element in an array
test_array = np.array([1, 2, 3])
repeated_array = np.repeat(test_array, 3)

print("np.repeat() :")
repeated_array

np.repeat() :


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [33]:
# np.ravel() converts a multi-dimensional array to a flattened 1D array
multi_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = np.ravel(multi_dimensional_array)

print("np.ravel() :")
flattened_array

np.ravel() :


array([1, 2, 3, 4, 5, 6])

In [34]:
# np.hsplit(), np.vsplit(), np.hstack(), np.vstack() are useful for splitting or stacking arrays vertically or horizontally
array_to_split = np.arange(1, 13).reshape(3, 4)

split_horizontal = np.hsplit(array_to_split, 2)
split_vertical = np.vsplit(array_to_split, 3)

stack_horizontal = np.hstack((split_horizontal[0], split_horizontal[1]))
stack_vertical = np.vstack((split_vertical[0], split_vertical[1], split_vertical[2]))

print("\nOriginal Array:\n\n", array_to_split)

print("\nnp.hsplit(), np.vsplit(), np.hstack(), np.vstack():")

print("\nSplit Horizontal:\n\n", split_horizontal)

print("\nSplit Vertical:\n\n", split_vertical)

print("\nStack Horizontal:\n\n", stack_horizontal)

print("\nStack Vertical:\n\n", stack_vertical)


Original Array:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.hsplit(), np.vsplit(), np.hstack(), np.vstack():

Split Horizontal:

 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

Split Vertical:

 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

Stack Horizontal:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Stack Vertical:

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
# np.transpose() is used as a multi-dimensional array
array_to_transpose = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = np.transpose(array_to_transpose)

print("np.transpose():\n\n", transposed_array)

np.transpose():

 [[1 4]
 [2 5]
 [3 6]]


In [36]:
# np.round() is used to round elements of an array to the nearest integer
array_to_round = np.array([1.23, 2.58, 3.91])
rounded_array = np.round(array_to_round)

print("np.round():\n\n", rounded_array)

np.round():

 [1. 3. 4.]


In [37]:
# np.expand_dims() is used to expand dimensions of an array
# np.squeeze() is used to squeeze dimensions of an array
array_to_expand_dimensions = np.array([1, 2, 3])
expanded_array = np.expand_dims(array_to_expand_dimensions, axis=1)

array_to_squeeze_dimensions = np.array([[[1], [2], [3]]])
squeezed_array = np.squeeze(array_to_squeeze_dimensions, axis=0)

print("np.expand_dims() & np.squeeze():")

print("\nOriginal Array:\n\n", array_to_expand_dimensions)

print("\nExpanded Array:\n\n", expanded_array)

print("\nSqueezed Array:\n\n", squeezed_array)

np.expand_dims() & np.squeeze():

Original Array:

 [1 2 3]

Expanded Array:

 [[1]
 [2]
 [3]]

Squeezed Array:

 [[1]
 [2]
 [3]]


In [38]:
# np.digitize() returns the indices of the bins to which each value in the input array belongs
array_to_digitize = np.array([1.5, 2.5, 5.5, 8.5])
bins = np.array([1, 3, 5, 7])
digitized_array = np.digitize(array_to_digitize, bins)

print("np.digitize():\n\n", digitized_array)

np.digitize():

 [1 1 3 4]
